apiVersion: kit/v1
kind: Pod
metadata:
  name: kit
spec:
  containers:
  - command:
    - go
    - run
    - ./demo/foo
    livenessProbe:
      tcpSocket:
        port: 8080
    name: foo
    ports:
    - hostPort: 8080
  - build:
      command:
      - go
      - build
      - .
      watch:
      - demo/bar
      workingDir: demo/bar
    command:
    - ./demo/bar/bar
    env:
    - name: PORT
      value: "9090"
    name: bar
    ports:
    - hostPort: 9090
    readinessProbe:
      httpGet:
        port: 9090
  - image: httpd
    name: baz
    ports:
    - containerPort: 80
      hostPort: 7070
    readinessProbe:
      httpGet:
        port: 7070
  - image: demo/qux
    name: qux
    ports:
    - containerPort: 80
      hostPort: 6060
    readinessProbe:
      httpGet:
        port: 6060
    volumeMounts:
    - mountPath: /work
      name: work
  - command:
    - sh
    - -c
    - |
      set -eux
      sleep 10
    name: kef
  initContainers:
  - command:
    - sleep
    - "1"
    name: init
  volumes:
  - hostPath:
      path: .
    name: work
