apiVersion: kit/v1
kind: Pod
metadata:
  annotations:
    help: https://github.com/alexec/kit
  name: kit
spec:
  tasks:
  - command:
    - go
    - run
    - ./demo/foo
    livenessProbe:
      tcpSocket:
        port: 8080
    name: foo
    ports:
    - hostPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
  - command:
    - go
    - build
    - -v
    - .
    name: build-bar
    watch:
    - demo/bar
    workingDir: demo/bar
  - command:
    - ./demo/bar/bar
    dependencies:
    - build-bar
    env:
    - name: PORT
      value: "9090"
    name: bar
    ports:
    - hostPort: 9090
    readinessProbe:
      httpGet:
        port: 9090
  - image: httpd
    name: baz
    ports:
    - containerPort: 80
      hostPort: 7070
    readinessProbe:
      httpGet:
        port: 7070
      initialDelaySeconds: 3
  - command:
    - ls
    - /work
    image: ubuntu
    name: init
    volumeMounts:
    - mountPath: /work
      name: work
  terminationGracePeriodSeconds: 3
  volumes:
  - hostPath:
      path: .
    name: work
