apiVersion: kit/v1
kind: Tasks
metadata:
  name: kit
spec:
  tasks:
  - name: build-go-demo
    command: go build -v .
    watch: main.go
    workingDir: demo/go

  - name: go-demo
    command: ./demo/go/go
    dependencies: build-go-demo
    env:
    - PORT=9090
    ports: "9090"
    readinessProbe: http://:9090

  - name: baz
    image: httpd
    ports: 80:10080
    log: baz.log
    readinessProbe: http://:10080?initialDelay=3s

  - name: docker
    command: ls /work
    image: ubuntu
    volumeMounts:
    - mountPath: /work
      name: work

  - name: error
    sh: |
      set -ex
      nopes

  - name: script
    sh: |
      set -eux
      echo "hello world"
      sleep 5

  - name: k8s
    manifests: testdata
    ports: "80:8080"

  - name: up
    dependencies: go-demo docker script k8s

  terminationGracePeriodSeconds: 3

  volumes:
  - hostPath:
      path: .
    name: work
