apiVersion: kit/v1
kind: Tasks
metadata:
  name: kit
spec:
  semaphores:
    two: 2
  tasks:
  - name: awn
    command: ./demo/awn/awn.sh
    ports: 9000
  - name: foo
    command: go run ./demo/foo
    ports: "8080"
    semaphore: two
  - name: build-bar
    command: go build -v .
    watch: demo/bar/main.go
    workingDir: demo/bar
    semaphore: two
  - name: bar
    command: ./demo/bar/bar
    dependencies: build-bar
    env:
    - PORT=9090
    ports: "9090"
    readinessProbe: http://:9090
    semaphore: two
  - name: baz
    image: httpd
    ports: 80:10080
    readinessProbe: http://:10080?initialDelay=3s
  - name: init
    command: ls /work
    image: ubuntu
    volumeMounts:
    - mountPath: /work
      name: work
  - name: error
    command:
    - sh
    - -c
    - |
      echo "hello" >&2
      echo "I'm an error" >&2
      sleep 3s
      exit 1
  - name: script
    command:
      - sh
      - -c
      - |
        echo "hello"
        sleep 5 & 
        echo "world"
  - name: up
    dependencies: awn foo bar baz script
  terminationGracePeriodSeconds: 3
  volumes:
  - hostPath:
      path: .
    name: work
