apiVersion: kit/v1
kind: Tasks
metadata:
  annotations:
    help: https://github.com/alexec/kit
  name: kit
spec:
  tasks:
  - command: go run ./demo/foo
    livenessProbe: tcp://:8080
    name: foo
    ports: "8080"
    readinessProbe: tcp://:8080
  - command: go build -v .
    name: build-bar
    watch: demo/bar
    workingDir: demo/bar
  - command: ./demo/bar/bar
    dependencies: build-bar
    env:
    - =
    name: bar
    ports: "9090"
    readinessProbe: http://:9090
  - image: httpd
    name: baz
    ports: 80:80
    readinessProbe: http://:7070?initialDelay=3s
  - command: ls /work
    image: ubuntu
    name: init
    volumeMounts:
    - mountPath: /work
      name: work
  - command: sh -c "exit 1"
    name: error
  - dependencies: foo bar baz
    name: up
  terminationGracePeriodSeconds: 3
  volumes:
  - hostPath:
      path: .
    name: work
