name: release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.22.0"
          cache: true

      - run: go test -v ./...

      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o kit_${{ github.ref_name }}_darwin_arm64 .
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=x86_64 go build -o kit_${{ github.ref_name }}_darwin_x86_64 .
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=i386 go build -o kit_${{ github.ref_name }}_linux_i386 .
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o kit_${{ github.ref_name }}_linux_arm64 .
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=x86_64 go build -o kit_${{ github.ref_name }}_linux_x86_64 .

      # create checksums.txt
      - run: shasum -a 256 kit_* > checksums.txt

      - name: Create a Release in a GitHub Action
        uses: comnoco/create-release-action@v2.0.5
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          files: |
            kit_${{ github.ref_name }}_darwin_arm64
            kit_${{ github.ref_name }}_darwin_x86_64
            kit_${{ github.ref_name }}_linux_i386
            kit_${{ github.ref_name }}_linux_arm64
            kit_${{ github.ref_name }}_linux_x86_64
            checksums.txt  
